# Generated by Django 6.0.2 on 2026-03-02 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, help_text='Unique student identifier (e.g. matric number).', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('course', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('has_voted', models.BooleanField(db_index=True, default=False)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('lock_until', models.DateTimeField(blank=True, help_text='Account locked until this time after exceeding failed attempts.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_id'],
            },
        ),
    ]
