# Generated by Django 5.1.15 on 2026-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="college",
            field=models.CharField(
                blank=True, default="", help_text="College affiliation (e.g. College of Engineering).", max_length=255
            ),
        ),
    ]
