# Generated by Django 5.1.15 on 2026-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_student_college"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="has_voted",
        ),
        migrations.AddField(
            model_name="student",
            name="is_admin",
            field=models.BooleanField(default=False, help_text="Designates whether this student has admin privileges."),
        ),
    ]
