# Generated by Django 5.1.15 on 2026-04-08 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_student_has_voted_student_is_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("electoral_board_head", "Electoral Board Head"),
                            ("electoral_board_operator", "Electoral Board Operator"),
                            ("tally_watcher", "Tally Watcher"),
                            ("auditor", "Auditor"),
                            ("technical_support", "Technical Support"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name shown in audit logs and UI.", max_length=255),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Inactive admin profiles cannot authenticate."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Profile",
                "verbose_name_plural": "Admin Profiles",
                "ordering": ["display_name"],
            },
        ),
    ]
