# Generated by Django 5.1.15 on 2026-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_election_position_candidate_redesign"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("position", "full_name"), name="unique_candidate_name_per_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="election",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))), name="election_end_time_after_start_time"
            ),
        ),
    ]
