# Generated by Django 5.1.15 on 2026-04-08 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_admin_profile_model"),
        ("elections", "0003_candidate_unique_candidate_name_per_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibleVoter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("college_snapshot", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Eligible Voter",
                "verbose_name_plural": "Eligible Voters",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("student_id_input", models.CharField(db_index=True, max_length=50)),
                ("full_name_input", models.CharField(blank=True, default="", max_length=255)),
                ("college_input", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("unmatched", "Unmatched"),
                            ("duplicate", "Duplicate"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Verification Record",
                "verbose_name_plural": "Verification Records",
                "ordering": ["imported_at"],
            },
        ),
        migrations.AddField(
            model_name="election",
            name="college",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required for college elections. Must be an official college name.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="election_type",
            field=models.CharField(
                choices=[("campus", "Campus"), ("college", "College")], db_index=True, default="campus", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="voter_roll_finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="voter_roll_finalized_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="position",
            name="category",
            field=models.CharField(
                choices=[
                    ("executive", "Executive"),
                    ("senate", "Senate"),
                    ("house_college", "House – College Representative"),
                    ("house_party", "House – Party-List Representative"),
                    ("college_executive", "College Executive"),
                    ("college_board", "College Board Member"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="election",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("college", ""), ("election_type", "campus")),
                    models.Q(("election_type", "college"), models.Q(("college", ""), _negated=True)),
                    _connector="OR",
                ),
                name="college_required_for_college_elections",
            ),
        ),
        migrations.AddField(
            model_name="eligiblevoter",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="voter_roll", to="elections.election"
            ),
        ),
        migrations.AddField(
            model_name="eligiblevoter",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="election_eligibility", to="accounts.student"
            ),
        ),
        migrations.AddField(
            model_name="verificationrecord",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_records",
                to="elections.election",
            ),
        ),
        migrations.AddField(
            model_name="verificationrecord",
            name="matched_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verification_records",
                to="accounts.student",
            ),
        ),
        migrations.AddConstraint(
            model_name="eligiblevoter",
            constraint=models.UniqueConstraint(fields=("election", "student"), name="unique_voter_per_election"),
        ),
        migrations.AddConstraint(
            model_name="verificationrecord",
            constraint=models.UniqueConstraint(
                fields=("election", "student_id_input"), name="unique_verification_per_election"
            ),
        ),
    ]
