# Generated by Django 6.0.2 on 2026-04-09 16:20

import apps.elections.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_eligiblevoter_verificationrecord_election_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'AY 2025-2026 First Semester'.", max_length=255)),
                ('academic_year', models.CharField(blank=True, default='', help_text="Academic year label, e.g. '2025-2026'.", max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=10)),
                ('total_imported', models.PositiveIntegerField(default=0)),
                ('imported_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registrar Import Batch',
                'verbose_name_plural': 'Registrar Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, help_text='Campaign/profile photo (max 2 MB, JPG/PNG/WebP).', null=True, upload_to=apps.elections.models.candidate_photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='platform_text',
            field=models.TextField(blank=True, default='', help_text='Short candidate platform or description.'),
        ),
        migrations.AddField(
            model_name='election',
            name='registrar_batch',
            field=models.ForeignKey(blank=True, help_text='The registrar import batch used for voter roll matching.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='elections.registrarimportbatch'),
        ),
    ]
