# Generated by Django 6.0.2 on 2026-04-15 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin_profile_model'),
        ('elections', '0007_election_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='voting_mode',
            field=models.CharField(choices=[('online', 'Online'), ('hybrid', 'Hybrid')], db_index=True, default='online', help_text='Hybrid elections accept online ballots plus closed-period onsite canvass imports.', max_length=10),
        ),
        migrations.CreateModel(
            name='HybridImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_type', models.CharField(choices=[('roster', 'Onsite Roster'), ('tally', 'Onsite Tally')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='failed', max_length=12)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('imported_by', models.CharField(blank=True, default='', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('overlap_count', models.PositiveIntegerField(default=0)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_import_batches', to='elections.election')),
            ],
            options={
                'verbose_name': 'Hybrid Import Batch',
                'verbose_name_plural': 'Hybrid Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnsiteParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='elections.hybridimportbatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onsite_participations', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Onsite Participation',
                'verbose_name_plural': 'Onsite Participations',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'student'), name='unique_onsite_participation_per_batch_student')],
            },
        ),
        migrations.CreateModel(
            name='OnsiteTally',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onsite_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallies', to='elections.hybridimportbatch')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onsite_tallies', to='elections.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onsite_tallies', to='elections.position')),
            ],
            options={
                'verbose_name': 'Onsite Tally',
                'verbose_name_plural': 'Onsite Tallies',
                'ordering': ['position__order', 'candidate__full_name'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'position', 'candidate'), name='unique_onsite_tally_per_batch_position_candidate')],
            },
        ),
    ]
