# Generated by Django 6.0.2 on 2026-03-02 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id_attempted', models.CharField(db_index=True, help_text='Student ID that was used in the attempt.', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('login_attempt', 'Login Attempt'), ('vote_cast', 'Vote Cast'), ('suspicious_activity', 'Suspicious Activity')], db_index=True, max_length=30)),
                ('details', models.TextField(blank=True, default='', help_text='Additional context about the event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
