# Generated by Django 5.1.15 on 2026-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_attempt", "Login Attempt"),
                    ("vote_cast", "Vote Cast"),
                    ("suspicious_activity", "Suspicious Activity"),
                    ("election_started", "Election Started"),
                    ("election_closed", "Election Closed"),
                    ("results_published", "Results Published"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
