# Generated by Django 5.1.15 on 2026-04-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_attempt", "Login Attempt"),
                    ("vote_cast", "Vote Cast"),
                    ("suspicious_activity", "Suspicious Activity"),
                    ("election_started", "Election Started"),
                    ("election_closed", "Election Closed"),
                    ("results_published", "Results Published"),
                    ("admin_login_attempt", "Admin Login Attempt"),
                    ("admin_logout", "Admin Logout"),
                    ("admin_permission_denied", "Admin Permission Denied"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
