# Generated by Django 6.0.2 on 2026-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_admin_audit_event_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_attempt', 'Login Attempt'), ('vote_cast', 'Vote Cast'), ('suspicious_activity', 'Suspicious Activity'), ('election_started', 'Election Started'), ('election_closed', 'Election Closed'), ('results_published', 'Results Published'), ('admin_login_attempt', 'Admin Login Attempt'), ('admin_logout', 'Admin Logout'), ('admin_permission_denied', 'Admin Permission Denied'), ('export_generated', 'Export Generated')], db_index=True, max_length=30),
        ),
    ]
