# Generated by Django 5.1.15 on 2026-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_ballot_ballotselection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballotselection",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
